# Generated by Django 4.2.7 on 2023-11-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='variation_category',
            field=models.CharField(choices=[('Color', 'color'), ('Size', 'size')], max_length=100),
        ),
    ]
