# Generated by Django 4.2.7 on 2023-11-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_variant_variation_value'),
        ('cart', '0002_alter_cart_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variant'),
        ),
    ]
